### ISSUE TITLE
[BUG] timeout between desktop and mobile (USUALLY)

### ISSUE THREAD

**Issue by icescoop12** [klept0/MS-Rewards-Farmer#41] opened 2023-12-02 16:35 UTC
getting error Timeout error usually between desktop searching and mobile searching although this has happened at the end of searching (desktop/mobile) and during daily set

*please not i have replaced my username with ****** below
## Actual Behavior
←[38;5;196m2023-12-02 16:27:14,288 [ERROR] TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.444
  (Session info: chrome=119.0.6045.200)
Stacktrace:
        GetHandleVerifier [0x007A72A3+45731]
        (No symbol) [0x00732D51]
        (No symbol) [0x0062880D]
        (No symbol) [0x0061ABF2]
        (No symbol) [0x0061AA9A]
        (No symbol) [0x006197F2]
        (No symbol) [0x00619FFA]
        (No symbol) [0x00623882]
        (No symbol) [0x00630BAA]
        (No symbol) [0x00633BA6]
        (No symbol) [0x0061A52C]
        (No symbol) [0x00630AC0]
        (No symbol) [0x0068B8C3]
        (No symbol) [0x00677DD6]
        (No symbol) [0x006531F6]
        (No symbol) [0x0065439D]
        GetHandleVerifier [0x00AB0716+3229462]
        GetHandleVerifier [0x00AF84C8+3523784]
        GetHandleVerifier [0x00AF214C+3498316]
        GetHandleVerifier [0x00831680+611968]
        (No symbol) [0x0073CCCC]
        (No symbol) [0x00738DF8]
        (No symbol) [0x00738F1D]
        (No symbol) [0x0072B2C7]
        BaseThreadInitThunk [0x75CE7BA9+25]
        RtlInitializeExceptionChain [0x7713BD2B+107]
        RtlClearBits [0x7713BCAF+191]
←[0m
Traceback (most recent call last):
  File "F:\Klept0_MS-Rewards-Farmer-master\main.py", line 42, in main
    earned_points = executeBot(currentAccount, notifier, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Klept0_MS-Rewards-Farmer-master\main.py", line 241, in executeBot
    desktopBrowser.utils.goHome()
  File "F:\Klept0_MS-Rewards-Farmer-master\src\utils.py", line 112, in goHome
    self.webdriver.get(BASE_URL)
  File "C:\Users\******\AppData\Roaming\Python\Python311\site-packages\undetected_chromedriver\__init__.py", line 629, in get_wrapped
    return orig_get(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\******\AppData\Roaming\Python\Python311\site-packages\undetected_chromedriver\__init__.py", line 665, in get
    return super().get(url)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in get
    self.execute(Command.GET, {"url": url})
  File "C:\Program Files\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.444
  (Session info: chrome=119.0.6045.200)
Stacktrace:
        GetHandleVerifier [0x007A72A3+45731]
        (No symbol) [0x00732D51]
        (No symbol) [0x0062880D]
        (No symbol) [0x0061ABF2]
        (No symbol) [0x0061AA9A]
        (No symbol) [0x006197F2]
        (No symbol) [0x00619FFA]
        (No symbol) [0x00623882]
        (No symbol) [0x00630BAA]
        (No symbol) [0x00633BA6]
        (No symbol) [0x0061A52C]
        (No symbol) [0x00630AC0]
        (No symbol) [0x0068B8C3]
        (No symbol) [0x00677DD6]
        (No symbol) [0x006531F6]
        (No symbol) [0x0065439D]
        GetHandleVerifier [0x00AB0716+3229462]
        GetHandleVerifier [0x00AF84C8+3523784]
        GetHandleVerifier [0x00AF214C+3498316]
        GetHandleVerifier [0x00831680+611968]
        (No symbol) [0x0073CCCC]
        (No symbol) [0x00738DF8]
        (No symbol) [0x00738F1D]
        (No symbol) [0x0072B2C7]
        BaseThreadInitThunk [0x75CE7BA9+25]
        RtlInitializeExceptionChain [0x7713BD2B+107]
        RtlClearBits [0x7713BCAF+191]

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome ver):
* Operating System and version:

**Comment by klept0** [comment] 2023-12-09 23:16
Is this still an issue or can this be closed?

**Comment by klept0** [comment] 2023-12-14 12:54
Dupe of Issue #10

**Closed by klept0** 2023-12-14 12:54 UTC
Labels: bug
