### ISSUE TITLE
Issue running script both master and dev

### ISSUE THREAD

**Issue by gh0sti** [klept0/MS-Rewards-Farmer#238] opened 2024-12-08 15:24 UTC
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I've cleared the sessions folder.

### Branch

develop

### Commit

latest

### Describe the bug

both Dev and Master 
can't run the script keeps erroring out, I've tried all the args -da, -v, -t mobile or desktop.

I keep Edge and chrome up to date
I use the upgrade from requirements.txt to make sure all of it is up to date.

### Copy and paste your error

Traceback (most recent call last):
  File "C:\Users\\Downloads\msrfd\main.py", line 39, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\Downloads\msrfd\main.py", line 234, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\Downloads\msrfd\src\browser.py", line 53, in __init__
    ) = GenerateUserAgent().userAgent(self.browserConfig, mobile)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\Downloads\msrfd\src\userAgentGenerator.py", line 50, in userAgent
    app = self.getAppComponents(mobile)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\Downloads\msrfd\src\userAgentGenerator.py", line 116, in getAppComponents
    edgeWindowsVersion, edgeAndroidVersion = self.getEdgeVersions()
                                             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\Downloads\msrfd\src\userAgentGenerator.py", line 143, in getEdgeVersions
    if stableProduct := next(
                        ^^^^^
  File "C:\Users\\Downloads\msrfd\src\userAgentGenerator.py", line 144, in <genexpr>
    (product for product in data if product["product"] == "Stable"),
                                    ~~~~~~~^^^^^^^^^^^
KeyError: 'product'

### Screenshots

error output is shown above, -v won't even populate the browser anymore

### Value of dashboard variable

most current dashboard

**Comment by cal4** [comment] 2024-12-09 01:43
Duplicate of #232

**Closed by cal4** 2024-12-09 01:43 UTC
Labels: bug, duplicate
