### ISSUE TITLE
Error while searching

### ISSUE THREAD

**Issue by MehmetCanWT** [klept0/MS-Rewards-Farmer#156] opened 2024-07-30 20:28 UTC
No chrome.exe and installed all reqs

Message: element click intercepted: Element <textarea class="b_searchbox" id="sb_form_q" name="q" enterkeyhint="go" rows="1" data-min-rows="1" aria-autocomplete="both" aria-label="Arama sözcüğünüzü buraya girin - Siz yazarken arama önerileri gösterilir" type="search" inputmode="search" value="..." maxlength="2000" dir="" autocapitalize="off" autocorrect="off" autocomplete="off" spellcheck="false" placeholder="Bana soru sorun...">fenerbahce maci hangi kanalda</textarea> is not clickable at point (929, 34). Other element would receive the click: <div class="bnp_overlay_wrapper"></div>
  (Session info: chrome=127.0.6533.73)
Stacktrace:
	GetHandleVerifier [0x00CBF653+11395]
	(No symbol) [0x00C9B7A4]
	(No symbol) [0x00BE1A43]
	(No symbol) [0x00C2B5C7]
	(No symbol) [0x00C299D9]
	(No symbol) [0x00C278CB]
	(No symbol) [0x00C26EAF]
	(No symbol) [0x00C1BFAF]
	(No symbol) [0x00C4719C]
	(No symbol) [0x00C1BA45]
	(No symbol) [0x00C47434]
	(No symbol) [0x00C603DC]
	(No symbol) [0x00C46F36]
	(No symbol) [0x00C1A276]
	(No symbol) [0x00C1AECD]
	GetHandleVerifier [0x00DC2403+1071667]
	GetHandleVerifier [0x00DCC9C4+1114100]
	GetHandleVerifier [0x00DC54B2+1084130]
	GetHandleVerifier [0x00CE013B+145259]
	(No symbol) [0x00CA1693]
	(No symbol) [0x00C9EFB8]
	(No symbol) [0x00C9F157]
	(No symbol) [0x00C9842E]
	BaseThreadInitThunk [0x75946709+25]
	RtlGetFullPathName_UEx [0x76F57D1D+173]
	RtlGetFullPathName_UEx [0x76F57CEB+123]

<traceback object at 0x0000020C8334C5C0>

**Comment by DeuX01** [comment] 2024-08-02 08:18
Getting a similar error today

⚠️ Error executing ********, please check the log
Message: element click intercepted: Element <textarea class="b_searchbox" id="sb_form_q" name="q" enterkeyhint="" rows="1" data-min-rows="1" aria-autocomplete="both" aria-label="Enter your search here - Search suggestions will show as you type" type="search" inputmode="search" value="..." maxlength="2000" dir="" autocapitalize="off" autocorrect="off" autocomplete="off" spellcheck="false" placeholder="Ask me anything...">triathlon olympia 2024</textarea> is not clickable at point (442, 46). Other element would receive the click: <div class="bnp_overlay_wrapper"></div>
  (Session info: chrome=126.0.6478.182)
Stacktrace:
#0 0x55901ca23c5a <unknown>
#1 0x55901c706e2c <unknown>
#2 0x55901c75a406 <unknown>
#3 0x55901c758246 <unknown>
#4 0x55901c755c27 <unknown>
#5 0x55901c754a60 <unknown>
#6 0x55901c74815f <unknown>
#7 0x55901c7765c2 <unknown>
#8 0x55901c747ad9 <unknown>
#9 0x55901c77678e <unknown>
#10 0x55901c795303 <unknown>
#11 0x55901c776363 <unknown>
#12 0x55901c746247 <unknown>
#13 0x55901c746b9e <unknown>
#14 0x55901c9ea22b <unknown>
#15 0x55901c9ee2d1 <unknown>
#16 0x55901c9d5ade <unknown>
#17 0x55901c9eee32 <unknown>
#18 0x55901c9ba77f <unknown>
#19 0x55901ca13618 <unknown>
#20 0x55901ca137f0 <unknown>
#21 0x55901ca22d8c <unknown>
#22 0x7ff3bedccac3 <unknown>

<traceback object at 0x7fa9121ff100>

**Comment by furret64** [comment] 2024-08-04 10:44
Happens to me as well

**Comment by jordicli** [comment] 2024-08-05 15:53
Same error here, I think it's the "accept cookies" dialog that's screwing up the script

**Comment by cal4** [comment] 2024-08-05 16:14
Do you have a full stack traceback? Look for something in the logs that starts with `src.` around the time you encounter the issue

Do you have a screenshot of the browser when the error happens?

**Comment by DeuX01** [comment] 2024-08-06 10:22
> Do you have a full stack traceback? Look for something in the logs that starts with `src.` around the time you encounter the issue
> 
> Do you have a screenshot of the browser when the error happens?

nothing with .src just this:

Traceback (most recent call last):
  File "/home/deux/configs/MS-Rewards-Farmer/main.py", line 39, in main
    earned_points = executeBot(currentAccount, args)
  File "/home/deux/configs/MS-Rewards-Farmer/main.py", line 248, in executeBot
    searches.bingSearches()
  File "/home/deux/configs/MS-Rewards-Farmer/src/searches.py", line 136, in bingSearches
    self.bingSearch()
  File "/home/deux/configs/MS-Rewards-Farmer/src/searches.py", line 173, in bingSearch
    searchbar.click()
  File "/home/deux/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/deux/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
  File "/home/deux/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/deux/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <textarea class="b_searchbox" id="sb_form_q" name="q" enterkeyhint="" rows="1" data-min-rows="1" aria-autocomplete="both" aria-label="Enter your search here - Search suggestions will show as you type" type="search" inputmode="search" value="..." maxlength="2000" dir="" autocapitalize="off" autocorrect="off" autocomplete="off" spellcheck="false" placeholder="Ask me anything...">pommel horse sport review</textarea> is not clickable at point (442, 46). Other element would receive the click: <div class="bnp_overlay_wrapper"></div>
  (Session info: chrome=127.0.6533.88)
Stacktrace:
#0 0x55c4d502b71a <unknown>
#1 0x55c4d4cfc640 <unknown>
#2 0x55c4d4d52926 <unknown>
#3 0x55c4d4d50836 <unknown>
#4 0x55c4d4d4e2b7 <unknown>
#5 0x55c4d4d4d15c <unknown>
#6 0x55c4d4d40c26 <unknown>
#7 0x55c4d4d6e8e2 <unknown>
#8 0x55c4d4d405d9 <unknown>
#9 0x55c4d4d6eaae <unknown>
#10 0x55c4d4d8d08a <unknown>
#11 0x55c4d4d6e683 <unknown>
#12 0x55c4d4d3ed71 <unknown>
#13 0x55c4d4d3f7de <unknown>
#14 0x55c4d4ff32ab <unknown>
#15 0x55c4d4ff7242 <unknown>
#16 0x55c4d4fe0665 <unknown>
#17 0x55c4d4ff7dd2 <unknown>
#18 0x55c4d4fc52af <unknown>
#19 0x55c4d501aeb8 <unknown>
#20 0x55c4d501b090 <unknown>
#21 0x55c4d502a4ec <unknown>
#22 0x7f042e120ac3 <unknown>

**Comment by cal4** [comment] 2024-08-09 04:07
Closing as duplicate of #169 since @SteveeeeeS has added some more troubleshooting there

**Closed** 2024-08-09 04:07 UTC
Labels: bug, duplicate
